package(default_visibility = ["//visibility:public"])

cc_library(
    name = "protobuf_matchers",
    testonly = True,
    hdrs = ["protobuf_matchers.h"],
    deps = [
        "@abseil-cpp//absl/memory",
        "@abseil-cpp//absl/strings",
        "@googletest//:gtest",
        "@protobuf",
    ],
)
